/**
 * UI-kit generator — emit a complete, runnable React + CSS-variables kit from a
 * preset (template or refined). Deterministic: same preset -> same kit bytes.
 *
 * The kit is the "most detailed enhanced UI" deliverable: a full component
 * library (every template in the preset, tokens resolved to CSS variables), a
 * `tokens.css` design-token file, an index barrel, and a README. Zero LLM.
 */

import type { Preset, DesignTokens } from "../types/index.js";

function pascalName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

export interface KitFile {
  path: string;
  content: string;
}

/**
 * Complete deterministic CSS-variables flattener for a token set. Covers every
 * section (colors -> `color-*`, blur, spacing incl. nested card/sidebar/settings
 * and array scale -> index, typography incl. scale/fontFamily/weight/lineHeight,
 * animation incl. duration/easing/transition). Same tokens -> same CSS.
 */
export function flattenTokensCss(tokens: DesignTokens): string {
  const out: string[] = [];
  const walk = (prefix: string[], node: unknown): void => {
    if (node === null || node === undefined) return;
    if (Array.isArray(node)) {
      node.forEach((v, i) => walk([...prefix, String(i)], v));
      return;
    }
    if (typeof node === "object") {
      for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
        walk([...prefix, k], v);
      }
      return;
    }
    const segs = prefix.map((s, i) => (i === 0 && s === "colors" ? "color" : s));
    out.push(`  --${segs.join("-")}: ${String(node)};`);
  };
  walk([], tokens);
  return `:root {\n${out.join("\n")}\n}\n`;
}

function toCssVar(path: string): string {
  // Match generateCSSVariables naming: top-level `colors` -> `color`,
  // dotted path joined with `-`.
  return `var(--${path.replace(/^colors\./, "color.").replace(/\./g, "-")})`;
}

export function generateKit(preset: Preset): KitFile[] {
  const files: KitFile[] = [];
  const tokensCss = flattenTokensCss(preset.tokens);
  files.push({ path: "tokens.css", content: tokensCss });

  const compNames: string[] = [];
  for (const comp of Object.values(preset.components)) {
    compNames.push(comp.name);
    const resolved = comp.template.replace(/\{\{token:([^}]+)\}\}/g, (_m, path: string) => toCssVar(path));
    files.push({
      path: `components/${comp.name}.tsx`,
      content: `/* Generated by OG-Glass UI kit (deterministic; zero LLM). Preset: ${preset.manifest.id} */\n${resolved}\n`,
    });
    for (const [vname, variant] of Object.entries(comp.variants ?? {})) {
      if (!variant.template) continue;
      const vResolved = variant.template.replace(/\{\{token:([^}]+)\}\}/g, (_m, path: string) => toCssVar(path));
      files.push({
        path: `components/${comp.name}.${vname}.tsx`,
        content: `/* Generated by OG-Glass UI kit (deterministic; zero LLM). Variant: ${vname} */\n${vResolved}\n`,
      });
    }
  }

  files.push({
    path: "index.ts",
    content:
      `// OG-Glass UI kit — ${preset.manifest.name}\n` +
      'import "./tokens.css";\n' +
      compNames.map((n) => `export { ${pascalName(n)} } from "./components/${n}";`).join("\n") +
      "\n",
  });

  files.push({
    path: "README.md",
    content: [
      `# ${preset.manifest.name} UI Kit`,
      "",
      preset.manifest.description,
      "",
      `Preset: \`${preset.manifest.id}\` (version ${preset.manifest.version})`,
      `Components: ${compNames.join(", ")}`,
      "",
      "```tsx",
      'import { Button } from "./index";',
      "// tokens.css is auto-imported — colors, type, spacing, radius, depth, motion",
      "```",
      "",
      "Tokens are CSS variables (see tokens.css) — follow the DESIGN.md contract exactly.",
    ].join("\n"),
  });

  return files;
}